name: phosopt
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - nibabel
  - pillow
  - trimesh
  - rtree
  - tqdm
  - pyyaml
  - scikit-optimize
  - scikit-learn
  - scikit-image
  - pandas
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
